### ISSUE TITLE
SCP 106 can't swap with SCP 096

### ISSUE THREAD

**Issue by Hamster12012** [BuildBoy12/ScpSwap#1]
Hi! So I've found weird bug.
While you spawn as SCP 106 and want to swap to SCP 096 it shows you that you cannot swap with yourself. I give a plugin config and screenshot.

**Comment by Hamster12012** [comment]
![image](https://user-images.githubusercontent.com/94808550/163066551-b9c54f74-c641-4128-a78e-7f70af1a5b5e.png)
 ScpSwap:
  is_enabled: true
  # Indicates whether debug messages should be shown.
  show_debug: false
  # The duration, in seconds, before a swap request gets automatically deleted.
  request_timeout: 20
  # The duration, in seconds, after the round starts that swap requests can be sent.
  swap_timeout: 60
  # Indicates whether a player can switch to a class if there is nobody playing as it.
  allow_new_scps: true
  # A collection of roles blacklisted from being swapped to.
  blacklisted_scps:
  - Scp0492
  # A collection of the names of custom scps blacklisted from being swapped to. This must match the name the developer integrated the SCP into this plugin's API with.
  blacklisted_names: []

**Comment by Hamster12012** [comment]
@BuildBoy12 

Using latest version of SCPSWAP for Exiled 5.0

**Comment by BuildBoy12** [comment]
Double check your translations file. Until the last update the default translation for 096 was Scp106.

**Comment by Hamster12012** [comment]
Fixed! Thank you so much. I am dumb and forgot about translation file
